import { Link } from 'react-router-dom';
import PageTitle from '../components/PageTitle';
import QuantitySelector from '../components/QuantitySelector';
import { useStore } from '../context/StoreContext';
import { money, productCover } from '../lib/assets';
export default function CartPage() {
  const { cart, subtotal, updateCart, removeCart } = useStore();
  return <main><PageTitle eyebrow="Your bag" title="Shopping cart" /><div className="max-w-[1110px] mx-auto px-6 py-10">{!cart.length ? <div className="bg-lgblue rounded-2xl p-12 text-center"><p className="text-dgblue">Your cart is empty.</p><Link to="/" className="inline-block bg-orange rounded-xl px-6 py-3 font-bold mt-5">Browse products</Link></div> : <div className="grid lg:grid-cols-[1fr_340px] gap-10"><div className="space-y-6">{cart.map((item) => <article key={item.id} className="flex gap-4 border-b border-gblue/30 pb-6"><img src={productCover(item)} alt={item.name} className="w-24 h-24 sm:w-32 sm:h-32 object-cover rounded-xl" /><div className="flex-1"><Link to={`/product/${item.slug}`} className="font-bold text-lg">{item.name}</Link><p className="text-dgblue text-sm mt-1">{money(item.price)} each</p><div className="max-w-40 mt-3"><QuantitySelector value={item.quantity} max={item.stock} onChange={(quantity) => updateCart(item.id, quantity)} /></div><button onClick={() => removeCart(item.id)} className="text-dgblue underline text-sm mt-3">Remove</button></div><b>{money(item.price * item.quantity)}</b></article>)}</div><aside className="bg-lgblue rounded-2xl p-6 h-fit"><h2 className="text-xl font-bold">Order summary</h2><p className="flex justify-between mt-6"><span>Subtotal</span><b>{money(subtotal)}</b></p><p className="flex justify-between mt-3 text-dgblue"><span>Shipping</span><span>{subtotal >= 100 ? 'Free' : money(8)}</span></p><p className="text-xs text-dgblue mt-4">Taxes are included for this demo.</p><Link to="/checkout" className="block text-center bg-orange rounded-xl py-4 font-bold mt-6">Continue to checkout</Link></aside></div>}</div></main>;
}
