create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category_id bigint not null references public.categories(id) on delete restrict,
  brand text not null,
  name text not null,
  description text not null,
  price_cents integer not null check (price_cents >= 0),
  compare_at_cents integer check (compare_at_cents is null or compare_at_cents >= price_cents),
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  image_set smallint not null default 1 check (image_set between 1 and 4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  address text not null default '',
  city text not null default '',
  postal_code text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.wishlist_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  customer_name text not null,
  email text not null,
  address text not null,
  city text not null,
  postal_code text not null,
  subtotal_cents integer not null check (subtotal_cents >= 0),
  shipping_cents integer not null check (shipping_cents >= 0),
  status text not null default 'confirmed' check (status in ('confirmed', 'processing', 'fulfilled', 'cancelled')),
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name text not null,
  unit_price_cents integer not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity > 0)
);

create index products_category_id_idx on public.products(category_id);
create index cart_items_user_id_idx on public.cart_items(user_id);
create index wishlist_items_user_id_idx on public.wishlist_items(user_id);
create index orders_user_created_at_idx on public.orders(user_id, created_at desc);
create index order_items_order_id_idx on public.order_items(order_id);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on table public.categories, public.products, public.profiles,
  public.cart_items, public.wishlist_items, public.orders, public.order_items
  from anon, authenticated;

grant select on table public.categories, public.products to anon, authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.cart_items, public.wishlist_items to authenticated;
grant select on table public.orders, public.order_items to authenticated;

create policy "Catalog categories are public"
  on public.categories for select to anon, authenticated using (true);
create policy "Catalog products are public"
  on public.products for select to anon, authenticated using (true);

create policy "Users can view their profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy "Users can create their profile"
  on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);
create policy "Users can update their profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Users can view their cart"
  on public.cart_items for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can add to their cart"
  on public.cart_items for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "Users can update their cart"
  on public.cart_items for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can remove from their cart"
  on public.cart_items for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can view their wishlist"
  on public.wishlist_items for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can add to their wishlist"
  on public.wishlist_items for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "Users can remove from their wishlist"
  on public.wishlist_items for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can view their orders"
  on public.orders for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can view their order items"
  on public.order_items for select to authenticated
  using (exists (
    select 1 from public.orders
    where public.orders.id = public.order_items.order_id
      and public.orders.user_id = (select auth.uid())
  ));

create or replace function public.checkout(
  customer_name text,
  customer_email text,
  delivery_address text,
  delivery_city text,
  delivery_postal_code text
) returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  new_order_id bigint;
  new_order_number text;
  order_subtotal integer;
  order_shipping integer;
begin
  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;

  if coalesce(trim(customer_name), '') = ''
    or coalesce(trim(customer_email), '') = ''
    or coalesce(trim(delivery_address), '') = ''
    or coalesce(trim(delivery_city), '') = ''
    or coalesce(trim(delivery_postal_code), '') = '' then
    raise exception 'Please complete every checkout field.';
  end if;

  -- Lock the product rows while validating and reserving stock so two
  -- simultaneous checkouts cannot oversell the same inventory.
  perform 1
  from public.products as product
  join public.cart_items as cart_item on cart_item.product_id = product.id
  where cart_item.user_id = current_user_id
  for update of product;

  if not exists (select 1 from public.cart_items where user_id = current_user_id) then
    raise exception 'Your cart is empty.';
  end if;

  if exists (
    select 1 from public.cart_items
    join public.products on public.products.id = public.cart_items.product_id
    where public.cart_items.user_id = current_user_id
      and public.cart_items.quantity > public.products.stock
  ) then
    raise exception 'One or more products no longer have enough stock.';
  end if;

  select sum(public.products.price_cents * public.cart_items.quantity)::integer
  into order_subtotal
  from public.cart_items
  join public.products on public.products.id = public.cart_items.product_id
  where public.cart_items.user_id = current_user_id;

  order_shipping := case when order_subtotal >= 10000 then 0 else 800 end;
  new_order_number := 'SNK-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));

  insert into public.orders (
    order_number, user_id, customer_name, email, address, city, postal_code,
    subtotal_cents, shipping_cents, status
  ) values (
    new_order_number, current_user_id, trim(customer_name), trim(customer_email),
    trim(delivery_address), trim(delivery_city), trim(delivery_postal_code),
    order_subtotal, order_shipping, 'confirmed'
  ) returning id into new_order_id;

  insert into public.order_items (order_id, product_id, product_name, unit_price_cents, quantity)
  select new_order_id, public.products.id, public.products.name,
    public.products.price_cents, public.cart_items.quantity
  from public.cart_items
  join public.products on public.products.id = public.cart_items.product_id
  where public.cart_items.user_id = current_user_id;

  update public.products
  set stock = public.products.stock - public.cart_items.quantity,
      updated_at = now()
  from public.cart_items
  where public.cart_items.user_id = current_user_id
    and public.products.id = public.cart_items.product_id;

  delete from public.cart_items where user_id = current_user_id;
  return new_order_number;
end;
$$;

revoke all on function public.checkout(text, text, text, text, text) from public, anon;
grant execute on function public.checkout(text, text, text, text, text) to authenticated;
